### ISSUE TITLE
Keyboard shortcuts issues on international keyboard layouts

### ISSUE THREAD

**Issue by tonifisler** [playcode/playcode#12]
I'm working with a Swiss-French Keyboard layout on MacOS and the `#` character is <kbd>alt</kbd>+<kbd>3</kbd>, which I can't write because the shortcut to focus the third pane takes over.

You should avoid using the <kbd>alt</kbd> key whenever possible because of issues with various international layouts 😉

**Comment by happierall** [comment]
Hi. Thank you.
How do you switch between tabs in chrome?

**Comment by tonifisler** [comment]
With the <kbd>cmd</kbd>+ <kbd>[1-9]</kbd> keys, I guess these ones are quite common to all layouts

**Comment by happierall** [comment]
I don't understand. Why? 
For write `#` you need press `shift` + `3`. Not?

**Comment by happierall** [comment]
Ok, I will cut this functionality. Useless.

**Comment by tonifisler** [comment]
On a Swiss keyboard (can't say for others), 

<kbd>shift</kbd>+<kbd>3<kbd> → `*`
<kbd>alt</kbd>+<kbd>3</kbd> → `#`

I'm sure there's also something hiding behind these shortcuts on every other international layout.

**Comment by happierall** [comment]
Fixed.
