### ISSUE TITLE
Jump to beginning of line

### ISSUE THREAD

**Issue by monavari-lebrecht** [playcode/playcode#15]
On Mac, it is not possible to jump to line beginning on pressing Cmd+Left. 

Jumping to the end of line is possible and jumping per word (Alt + Left/Right) is possible as well.

**Comment by monavari-lebrecht** [comment]
Seems to be an issue of my mac. It doesnt work anymore in sublime either anymore. 😒

**Comment by monavari-lebrecht** [comment]
my fault ... it is caused by Playcode and more... after I started Playcode Desktop app, it is not possible anymore to jump to line beginning even in other applications. Whenever I quit Playcode again, the keycommand Cmd+Left is valid again.

**Comment by happierall** [comment]
Haha, yes, very strange bug

**Comment by ianberdin** [comment]
It works now!
