### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by ngarbezza** [playcode/playcode#22]
Hi! I'd like to use Playcode to present to my students, but I use a projector and it's hard to see the dark theme

The rest of the tool suites perfect for my class, but the dark theme makes it difficult

**Comment by happierall** [comment]
Hello Nahuel,
We will implement light theme 😏🙏

Thank you for your helpful idea 💡

**Comment by Harriethijssen** [comment]
Vote+1

**Comment by ianberdin** [comment]
Done.
