### ISSUE TITLE
Ability to turn on/off files

### ISSUE THREAD

**Issue by ngarbezza** [playcode/playcode#23]
I use to work with Playcode with several example files in the same project. Most of them do `console.log()` statements. It would be nice to temporarily "disable" scripts (so they don't get executed) so:

* Results do not appear in the console
* If there's a syntax error (or errors of any kind) I can continue running other examples

It can be a simple toggle button just near the already existing trash icon .

**Comment by happierall** [comment]
I think, you should wrap your scripts and init separately.
```javascript
// step_1.js
function step_1() {
  console.log('Step 1')
}
```
```javascript
// init.js
step_1()
step_2()
//step_3() // Disabled
```


[Example](https://playcode.io/129270?tabs=console&init.js&output)
