### ISSUE TITLE
source for self-hosting?

### ISSUE THREAD

**Issue by bkis** [playcode/playcode#25]
Hi there! I'm sorry i have to spam your issue system for a simple question, but i see there's no open code in this repo. I like the app an i'd like to use it in education, but i'd rather host on my own server (closed, private instance) for this purpose. Is there any way to do that?

**Comment by happierall** [comment]
Hello Börge!
Can you explain: why do you want private projects?

May be we will implement features for that.



пн, 3 дек. 2018 г. в 13:49, Börge Kiss <notifications@github.com>:

**Comment by bkis** [comment]
It's not only about private projects (although that would be nice, too). I am talking about the fact that there is no code online here in your repo, but only a readme. Are you planning to open source the code of this app?

**Comment by happierall** [comment]
Sorry, but we will not.

**Comment by bkis** [comment]
ok, thanks anyway

**Comment by LongJohn-Silver** [comment]
Hey, @bkis, if you are interested there's a libre project which works almost like this if you would like to try it out.

https://github.com/jojowwbb/PenEditor/
