### ISSUE TITLE
Support for private project 

### ISSUE THREAD

**Issue by shahidcodes** [playcode/playcode#26]
Why playcode does not have private projects ?

**Comment by happierall** [comment]
Hello Shahid.
Can you describe your case for the private project?

**Comment by shahidcodes** [comment]
There are cases like we want to develop something internally then later make it public or some private projects or experiments.

**Comment by happierall** [comment]
We?
Do you need share access to to private project?

**Comment by happierall** [comment]
Thank you Shahid.
I will add private projects in a 1-2 month.

вс, 27 янв. 2019 г. в 16:27, Shahid Kamal <notifications@github.com>:

**Comment by shahidcodes** [comment]
Thanks it'll be very much helpful.
