### ISSUE TITLE
stylus broken

### ISSUE THREAD

**Issue by Akiyamka** [playcode/playcode#30]
I can not use brackets in the code.
For example:
`transform: rotate(-90deg);` will crush with
```
main.46dbdd6.js:1 Stylus Compile Error: Cannot read property 'nodes' of undefined
```
This is strange because I use the stylus locally every day and it never broke from the similar code.
Looks like some king of unofficial parser trying execute this like stylus function.
I try use escape char for workaround:
`transform: rotate\(-90deg\);`
After that error gone, but now compiled css broken and now work in browser (reason - extra whitespaces):
`rotate ( -90deg )`

**Comment by happierall** [comment]
Hello Alexander.

Fixed. Thank you!

**Comment by happierall** [comment]
Problem solved?

**Comment by Akiyamka** [comment]
Yes, thanks for the quick fix!
