### ISSUE TITLE
Console view

### ISSUE THREAD

**Issue by lcherone** [playcode/playcode#34]
On https://playcode.io/my-projects can you add console view, 99% of my saves are just outputting to console, it would be nice to see that so they can be cleaned up vs going in and seeing what it is.

Also a delete multiple would be nice.

![Screenshot_2020-04-18_18-30-29](https://user-images.githubusercontent.com/3892806/79644731-b59ef500-81a2-11ea-9b9d-e6043d943ea9.png)

**Comment by ianberdin** [comment]
Hello, did you try a new console view?

Ruslan Ianberdin,
Founder of playcode.io

**Comment by lcherone** [comment]
Looks great, nice work
