### ISSUE TITLE
Tab freeze

### ISSUE THREAD

**Issue by semaphore8** [playcode/playcode#35]
Hi

When I try to `console.log` `range()` function with negative 3rd argument, I get My Chrome tab freeze, can't even open devtools.

i.e. `console.log(range(1,10,-1))`

Code:
 
```js
const range = (start, end, step = 1) => {
  let arr = [start]
  let current = start + step
  while (current <= end) {
    arr.push(current)
    current+=step
  }
  return arr
}

console.log(range(1,10))
```

Editor URL https://playcode.io/593531/

**Comment by lcherone** [comment]
`1 + -1` is 0, you have an infinite loop.

`console.log(1 + -1 + -1 + -1 + -1 + -1 + -1) // -5`

**Comment by semaphore8** [comment]
Yes, definitely it is. Thanks.
