### ISSUE TITLE
Code auto-format on save

### ISSUE THREAD

**Issue by Satak** [playcode/playcode#36]
Is there auto-format option somewhere? Would be great to have some prettier type settings there so it would automatically format the code on save.

**Comment by lcherone** [comment]
`Ctrl + Sft + L` or click the button top right of the editor. 

![Screenshot_2020-05-27_18-50-29](https://user-images.githubusercontent.com/3892806/83054884-024fd880-a04b-11ea-999e-882491408173.png)

**Comment by Satak** [comment]
Better would be an option to auto-format on `Ctrl + s`, all IDE's have that. It's too cumbersome to press two key commands just to format your code.

**Comment by ianberdin** [comment]
It is impossible to set cmd + s in browser.
Most of browsers do not allow to remap important hotkeys like ctr + r not ctrl + s.
