### ISSUE TITLE
Loop bug?

### ISSUE THREAD

**Issue by pyrrhicman** [playcode/playcode#38]
Hi, It seems that loops doesn't work
even this:

`
let ss = 0
for (ss = 0 ; ss < 10 ; ss++) {
  console.log(ss)
}
`

**Comment by lcherone** [comment]
Looks like its missing `;` 

```
let i 
for (i = 0; i < 10; ++i) {
  console.log(i);
}

// or
for (let ii = 0; ii < 10; ++ii) {
  console.log(ii)
}

```

**Comment by pyrrhicman** [comment]
![Screenshot 2020-06-26 at 19 40 28](https://user-images.githubusercontent.com/32340808/85880575-e758bb80-b7e4-11ea-9d4d-7cc2853e0f31.png)

am I missing something because it really doesn't work :( 
I just changed the number;

**Comment by ianberdin** [comment]
I'm on it, thanks!

**Comment by ianberdin** [comment]
Fixed! 🙏
