### ISSUE TITLE
"New Version Available" popup message doesn't allow going back to the code.

### ISSUE THREAD

**Issue by julesra** [playcode/playcode#39]
Hi, I love this online app !!

I'm having some trouble with the "New Version Available" popup message - when it shows up, I lose all my code because none of the buttons allows me to go back to my coding. See screenshot below. Clicking on "Restart Later" or on "X" causes the popup to reappear without any time for me to save my work. It's frustrating to lose code, I hope it gets fixed, thank you !

PS: Browser is Firefox 75.0

![image](https://user-images.githubusercontent.com/10662283/86287461-34a6a580-bbb6-11ea-97dd-da380ea74db9.png)

**Comment by ianberdin** [comment]
Hello there!
I'm so sorry about it :(

I will investigate!

**Comment by ianberdin** [comment]
Fixed! Thanks 🙏

**Comment by julesra** [comment]
Glad to hear, you're welcome !
