### ISSUE TITLE
How to disable bug finder?

### ISSUE THREAD

**Issue by ghost** [playcode/playcode#40]
Is is possible to disable the bugfinder, it would be really nice.

**Comment by ianberdin** [comment]
Does it distract you or something? Can you show an example?

**Comment by novachief101** [comment]
Sorry for the late reply. When I use too many parameters for a function, it really annoys me. I know I can use ESLint block comments; is there any other way?

**Comment by ianberdin** [comment]
Yea, for sure.
Turn off `syntax validation`.
<img width="748" alt="image" src="https://user-images.githubusercontent.com/2521933/171414332-f7b1865c-8a0f-48a0-88b6-f913a5a09a52.png">
