### ISSUE TITLE
Console time/timeEnd support?

### ISSUE THREAD

**Issue by kovalromank** [playcode/playcode#42]
It seems like the methods console.time/timeEnd aren't supported by the console in the page.

Code:
```javascript
function drawPoints() {
  console.time('drawPoints');
  _drawPoints();
  console.timeEnd('drawPoints');
}
```

Chrome console:
![Screenshot from 2020-09-17 00-32-41](https://user-images.githubusercontent.com/17420250/93420634-5e9a6a80-f87d-11ea-9b0f-aa2aa1fbc14f.png)

Playcode console:
![Screenshot from 2020-09-17 00-33-32](https://user-images.githubusercontent.com/17420250/93420682-72de6780-f87d-11ea-9c8c-0ef9bff2465b.png)

The values in the playcode console are always increasing.

**Comment by ianberdin** [comment]
It's strange. I will check later.

**Comment by ianberdin** [comment]
It should works now.
