### ISSUE TITLE
Backdrop-Filter does ignores clip-path on Playcode.io only.

### ISSUE THREAD

**Issue by uplusion23** [playcode/playcode#43]
Backdrop-filter bleeds out of the clip-path on Playcode.io. I'm using Chrome 85, and testing the same code on CodePen.io is successful, whereas the issue seems to persist in Playcode.io exclusively.

Link to the PlayCode.io [Here](https://playcode.io/674321/)
Link to the CodePen.io [Here](https://codepen.io/uplusion23/pen/KKzGQxE)

**Comment by ianberdin** [comment]
Codepen uses autoprefixer. PlayCode doesn't. Can you try add prefixes?

**Comment by uplusion23** [comment]
It seemed to happen even using the -webkit- prefix, I couldn't find any
differences between the two, other than CodePen seems to render the result
in a <div> rather than an iframe. I was hoping to see if the issue
persisted on the deploy page but sadly that seems to be down for
maintenance I'm assuming.

**Comment by ianberdin** [comment]
Closed as stale.
