### ISSUE TITLE
Gray theme comments aren't italicized

### ISSUE THREAD

**Issue by mrjbq7** [playcode/playcode#48]
The ``Blue``, ``Light``, and ``Dark`` themes have italicized comments in the syntax highlighting.

But the ``Gray`` theme does not have them.

If that's an oversight, could you make them italic?

**Comment by ianberdin** [comment]
Hi! 
Thanks for the feedback.
I see this Gray theme as a stand aside thing with different view.
So I do not try to  make it similar to others.

Why should it be italic?

**Comment by ianberdin** [comment]
Hi!
The comments fixed.
Thanks.
