### ISSUE TITLE
svg's unable to display

### ISSUE THREAD

**Issue by ricky11** [playcode/playcode#49]
I've tried to embed an svg file after uploading but it fails to display in both chrome and safari, 
i am pretty sure i didn't get the path wrong, please have a look at the link and the broken image

` <img id="logo" src="./logo.svg"/> `

https://playcode.io/youface/

**Comment by ianberdin** [comment]
Hi! 
Thank you for your feedback! 
Please try to restart page, it should help.

**Comment by ianberdin** [comment]
Just checked. It works: https://playcode.io/957399/
