### ISSUE TITLE
Allow to autoformat code on save (ctrl/cmd + s)

### ISSUE THREAD

**Issue by Ayub-Begimkulov** [playcode/playcode#52]
Recently switched from codesandbox to playcode, and so far the experience has been really awesome. The playground works really fast and provides an awesome experience for me and my mentees. 

However, there is a feature that I really miss from codesandbox and my editor — auto formatting on save. I found out that there was an issue about it (https://github.com/playcode/playcode/issues/36). And it's closed with a following comment:

```
It is impossible to set cmd + s in browser.
Most of browsers do not allow to remap important hotkeys like ctr + r not ctrl + s.
```

But, it seems like right now the `CMD/CTRL + S` is already overwritten, cause each time I press it, there is green toaster that show that changes have been saved (screen below). 

![image](https://github.com/playcode/playcode/assets/46418811/c6a18333-a894-4749-9444-13074317c9f6)

So It would be really awesome if there was an option in the settings to allow formatting when we manually press save shortcut (`CMD/CTRL + S`).

**Comment by ianberdin** [comment]
Hi,
Thank you for the idea.
It's implemented.
