### ISSUE TITLE
Add an option to disable confetti when formatting code.

### ISSUE THREAD

**Issue by Ayub-Begimkulov** [playcode/playcode#53]
Recently switched from codesandbox to playcode, and so far the experience has been really awesome. The playground works really fast and provides an awesome experience for me and my mentees.

But there is one thing that distracts me quite a bit — confettis when formatting code. Also I use playcode to record screencast/tutorial and it might also distract the view too. 

It would be really awesome if there was an option to turn off confettis in the settings. 

![telegram-cloud-photo-size-2-5238166729115424978-y](https://github.com/playcode/playcode/assets/46418811/6e3e75b6-eaea-4847-9850-bd982a2897b0)

**Comment by ianberdin** [comment]
I will add it to the backlog. Thank you.Ruslan IanberdinOn Jan 3, 2024, at 7:14 PM, Ayub Begimkulov ***@***.***> wrote:﻿
Recently switched from codesandbox to playcode, and so far the experience has been really awesome. The playground works really fast and provides an awesome experience for me and my mentees.
But there is one thing that distracts me quite a bit — confettis when formatting code. Also I use playcode to record screencast/tutorial and it might also distract the view too.
It would be really awesome if there was an option to turn off confettis in the settings.
telegram-cloud-photo-size-2-5238166729115424978-y.jpg (view on web)

**Comment by ianberdin** [comment]
It is disabled if you use shortcut cmd/ctrl + s
