### ISSUE TITLE
Add an option to hide "save toaster"

### ISSUE THREAD

**Issue by Ayub-Begimkulov** [playcode/playcode#54]
Recently switched from codesandbox to playcode, and so far the experience has been really awesome. The playground works really fast and provides an awesome experience for me and my mentees.

One thing that I think would be useful is to allow disabling the toaster that is shown on top when we manually save (with `CTRL/CMD + S`). After using vscode and codesandbox I'm used to always pressing cmd+s (and many more people too) after I write something. Which makes this toaster a lot more distracting. 

I think it would be cool if there was an option too turn this feature off.

![image](https://github.com/playcode/playcode/assets/46418811/da692291-337d-4203-9b45-0056920e3024)

**Comment by ianberdin** [comment]
Hi, Thank you for your feedback! The point is, you do not need to save your project. It saves in Real-time. This toast is just a backward compatible reminder.Ruslan IanberdinOn Jan 3, 2024, at 7:23 PM, Ayub Begimkulov ***@***.***> wrote:﻿
Recently switched from codesandbox to playcode, and so far the experience has been really awesome. The playground works really fast and provides an awesome experience for me and my mentees.
One thing that I think would be useful is to allow disabling the toaster that is shown on top when we manually save (with CTRL/CMD + S). After using vscode and codesandbox I'm used to always pressing cmd+s (and many more people too) after I write something. Which makes this toaster a lot more distracting.
I think it would be cool if there was an option too turn this feature off.

**Comment by ianberdin** [comment]
It's removed.
