### ISSUE TITLE
I can not publish the project.

### ISSUE THREAD

**Issue by webhacck** [playcode/playcode#7]
Hi, I have question.

It is stop work when I 3 to 4 characters are entered for name input.
![picture01](https://cloud.githubusercontent.com/assets/16042063/22282211/5870d0a4-e31e-11e6-974a-e3678b28ead2.jpg)

And then, when I checked the Public URL, I could not see it.
![picture02](https://cloud.githubusercontent.com/assets/16042063/22282290/cda2d570-e31e-11e6-9af0-af8f8ef09e68.jpg)

Could you please help me?

I use ...
- Chrome Browser ver.55
- Chromebook (acer)

**Comment by happierall** [comment]
Hi, thank you.
But it's work: http://sss.playcode.io/

How can I reproduce it?
Show me project link (with id)

**Comment by happierall** [comment]
http://aaab.playcode.io/
Works to

**Comment by webhacck** [comment]
Thank you for your reply.
Perhaps, It may be a problem with my PC only. (I do not know the reason...)
I tried to record my screen.
https://www.youtube.com/watch?v=tafFBx-J-2A
(only movie, Because I can not speak English well.)

I will check a little more...

**Comment by happierall** [comment]
Because your project isn't created.
Try change anything in files and after that change public name.

**Comment by happierall** [comment]
And you found new bug: [unathorized user and without changed anything in files see project name input as enabled](https://github.com/playcode/playcode/issues/9)

**Comment by webhacck** [comment]
Thanks for the advice!
After changing something, I was able to use the public name.
thank you very much.
